---
title: "R Notebook"
output: html_notebook
---

# Load Packages
```{r}
library(rvest)
library(dplyr)
library(nflfastR)
library(DT)
```

# Load Play-By-Play Data
```{r}
pbp <- load_pbp(2025)
```


# Get Win% and PD Data
## Get Team Abbreviations
```{r}
team_abbr <- c(
  "Arizona Cardinals" = "ARI",
  "Atlanta Falcons"  = "ATL",
  "Baltimore Ravens" = "BAL",
  "Buffalo Bills"    = "BUF",
  "Carolina Panthers"= "CAR",
  "Chicago Bears"    = "CHI",
  "Cincinnati Bengals" = "CIN",
  "Cleveland Browns" = "CLE",
  "Dallas Cowboys"   = "DAL",
  "Denver Broncos"   = "DEN",
  "Detroit Lions"    = "DET",
  "Green Bay Packers"= "GB",
  "Houston Texans"   = "HOU",
  "Indianapolis Colts" = "IND",
  "Jacksonville Jaguars" = "JAX",
  "Kansas City Chiefs" = "KC",
  "Las Vegas Raiders" = "LV",
  "Los Angeles Chargers" = "LAC",
  "Los Angeles Rams" = "LA",
  "Miami Dolphins"   = "MIA",
  "Minnesota Vikings"= "MIN",
  "New England Patriots" = "NE",
  "New Orleans Saints" = "NO",
  "New York Giants"  = "NYG",
  "New York Jets"    = "NYJ",
  "Philadelphia Eagles" = "PHI",
  "Pittsburgh Steelers" = "PIT",
  "San Francisco 49ers" = "SF",
  "Seattle Seahawks" = "SEA",
  "Tampa Bay Buccaneers" = "TB",
  "Tennessee Titans" = "TEN",
  "Washington Commanders" = "WAS"
)
```

## Scrape Webpage
```{r}
url <- "https://www.profootballnetwork.com/nfl/standings/league/2025"

page <- read_html(url)

# grab *all* tables on the page
tables <- page %>% html_nodes("table") %>% html_table(fill = TRUE)

tables

# Take the first (main) standings table
standings <- tables[[1]]

# Promote first row to headers
colnames(standings) <- standings[1, ]

# Drop the first row (now redundant)
standings <- standings[-1, ]

colnames(standings)[1] <- "team"

standings <- standings %>%
  mutate(pct = as.numeric(PCT), pf = as.numeric(PF), pa = as.numeric(PA)) %>%
  select(team, pct, pf, pa) %>%
  mutate(diff = pf-pa) %>%
  mutate(team = team_abbr[team]) %>%
  select(team, pct, diff)

standings
```







# Get EPA Data
## Create get_epa Function
```{r}
get_epa <- function(team_input) {
  off_output <- pbp %>%
    filter(posteam == team_input) %>%
    group_by(posteam) %>%
    summarize(off_epa = round(mean(epa, na.rm = TRUE), 3)) %>%
    rename(team = posteam)
  
  def_output <- pbp %>%
    filter(defteam == team_input) %>%
    group_by(defteam) %>%
    summarize(def_epa = round(mean(epa, na.rm = TRUE), 3)) %>%
    rename(team = defteam)

combined <- off_output %>%
  left_join(def_output, by = "team")

return(combined)
}
get_epa("LAC")
```

## Loop Through Teams
```{r}
teams <- pbp %>%
  filter(!is.na(posteam)) %>%
  distinct(posteam) %>%
  arrange(posteam) %>%
  pull(posteam)

teams

epa_results <- tibble()
for (i in teams) {
  epa_results <- bind_rows(epa_results, get_epa(i))
}
epa_results
```

## Combine For Initial Values
```{r}
initial_values <- standings %>%
  left_join(epa_results, by = "team")
initial_values
```


# Get initial Ratings
```{r}
min_diff <- min(initial_values$diff)
max_diff <- max(initial_values$diff)
diff_range <- max_diff - min_diff

get_init_ratings <- function(input_df) {
  output <- input_df %>% mutate(
    pct = round(pct * 2, 2), # min: 0%, mean: 50%, max: 100%
    diff = round(((diff-min_diff) / diff_range) * 2, 2), # min: min_diff, mean: ?, max: max_diff
    off_epa = round(pmax(pmin((off_epa + .15) * 6.67, 2), 0), 2), # min: -.15, mean: 0, max: .15
    def_epa = round(pmax(pmin((def_epa - .15) * -6.67, 2), 0), 2), # min: .15, mean: 0, max: -.15
    total = pct + diff + off_epa + def_epa
  ) %>%
    arrange(-total)
  return(output)
}

initial_ratings <- get_init_ratings(initial_values)
initial_ratings
```





# Get SOS
## Get Opponents
```{r}
get_opponents <- function(team_input) {
  output <- pbp %>%
  filter(posteam == team_input) %>%
  group_by(game_id) %>%
  slice_min(., order_by = play_id) %>% # Take only first play
  ungroup() %>%
  pull(defteam)
return(output)
}

sos_results <- tibble()
for (i in teams) {
  opp <- get_opponents(i)
  ratings <- c()
  for (j in opp) {
    opp_rating <- initial_ratings %>%
      filter(team == j) %>%
      pull(total)
    ratings <- append(ratings, opp_rating)
  }
  mean_rating <- round(mean(ratings), 2)
  rating_tibble <- tibble(i, mean_rating)
  sos_results <- bind_rows(sos_results, rating_tibble)
}
sos_results <- sos_results %>%
  rename(team = i, sos = mean_rating)
sos_results
```

## Get SOS
```{r}
min_sos <- min(sos_results$sos)
max_sos <- max(sos_results$sos)
sos_range <- max_sos - min_sos
get_sos <- function(input_df) {
  output <- input_df %>%
    mutate(
      sos = round((((sos - min_sos) / sos_range) * 2), 2)
        )
  return(output)
}
sos_ratings <- get_sos(sos_results)
sos_ratings
```


```{r}
final_ratings <- initial_ratings %>%
  left_join(sos_ratings, by = "team") %>%
  select(-total) %>%
  mutate(total = pct + diff + off_epa + def_epa + sos) %>%
  arrange(-total)
datatable(final_ratings)
```

